services:
  web:
    build: .
    container_name: restaurant_web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=server=db;database=restaurantdb;user=root;password=1234;TreatTinyAsBoolean=false;
    restart: always

  db:
    image: mysql:8.3
    container_name: restaurant_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MySecret123
      MYSQL_DATABASE: restaurant_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
